mod 19/proj 1/mysite/cats/urls.py
from django.urls import path
from . import views
app_name = 'cats'

urlpatterns = [
    path('', views.CatList.as_view(), name='cats_list'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/ delete', views.CatDelete.as_view(), name='cat_delete'),

    path('lookup/', views.BreedList.as_view(), name = 'breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update',views.BreedUpdate.as_view(), name = 'breed_update'),
    path('lookup/<int:pk>/delete',views.BreedDelete.as_view(), name = 'breed_delete'),
]

mod 19/proj 1/mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path("", TemplateView.as_view(template_name='home/main.html')), # including static html file
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mod 19/proj 1/mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.
class Breed(models.Model):
    name = models.CharField(
        max_length = 200,
        validators = [
            MinLengthValidator(2, "Breed must be greater than 1 character")
        ]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
        max_length = 200,
        validators = [
            MinLengthValidator(2, "Nickname must be greater than 1 character")

        ]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length = 300)
    breed = models.ForeignKey('Breed', on_delete = models.CASCADE, null = False)

    def __str__(self):
        return self.nickname

mod 19/proj 1/mysite/cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from cats.models import Cat, Breed



# Create your views here.

class CatList(LoginRequiredMixin, View):
    def get(self, request):
        breed_count = Breed.objects.count()
        cat_list = Cat.objects.all()
        ctx = {'breed_count': breed_count, 'cats_list': cat_list}
        return render(request, 'cats/cats_list.html', ctx)


class BreedList(LoginRequiredMixin, View):
    def get(self, request):
        breed_list = Breed.objects.all()
        ctx = {'breed_list': breed_list}
        return render(request, 'cats/breed_list.html', ctx)

class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy("cats:cats_list")


class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy("cats:cats_list")

class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy("cats:cats_list")

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:cats_list')

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:cats_list')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:cats_list')

mod 19/proj 1/mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:cats_list' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mod 19/proj 1/mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:cats_list' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mod 19/proj 1/mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Breeds List</h1>
  {% if breed_list %}
  <ul>
    {% for breed in breed_list %}
      <li>
          {{ breed.name }}
         (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
          <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no breeds in the library.</p>
  {% endif %}
  <p><a href="{% url 'cats:breed_create' %}">Add a Breed</a></p>
  <p>
    <a href="{% url 'cats:cats_list' %}">Back to cats</a>
  </p>
{% endblock %}

mod 19/proj 1/mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:cats_list' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mod 19/proj 1/mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
{% if user.is_authenticated %}
  <p>Welcome, {{ user.first_name }}!</p>
{% else %}
  <p>Welcome, guest!</p>
{% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:cats_list' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mod 19/proj 1/mysite/cats/templates/cats/cats_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Cats List</h1>
  {% if cats_list %}
  <ul>
    {% for cat in cats_list %}
      <li>
          {{ cat.nickname }} ({{ cat.breed }})
          (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
          <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) <br/>
          {{cat.weight }} pounds ({{ cat.foods }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cats in the library.</p>
  {% endif %}
  <p>
    {% if breed_count > 0 %}
      <a href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
      Please add a breed before you add an Cat.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) |
    <a href="{% url 'cats:breed_create' %}">Add a breed</a>
  </p>
{% endblock %}